var AIBlocker = AIBlocker || {};

AIBlocker.SETTINGS = {
  coverAllPosts: true,
  failureThreshold: 3,
  minTextLength: 80,
  scanDebounceMs: 300,
  debug: true,

  detectors: {
    lackOfBurstiness: true,
    ruleOfThree: true,
    overExplaining: true,
    flawlessYetEmpty: true,
  },

  burstiness: {
    minSentences: 4,
    maxCoefficientOfVariation: 0.48,
  },

  ruleOfThree: {
    minMatches: 2,
  },

  overExplaining: {
    maxFillerPer100Words: 2.5,
    phrases: [
      "it's important to note",
      "it is important to note",
      "in today's",
      "in today's world",
      "in today's fast-paced",
      "leverage",
      "furthermore",
      "moreover",
      "that being said",
      "at the end of the day",
      "needless to say",
      "it goes without saying",
      "when it comes to",
      "in order to",
      "it is worth noting",
      "it's worth noting",
      "as we navigate",
      "in this ever-changing",
      "delve into",
      "dive into",
      "game changer",
      "game-changer",
      "unlock the potential",
      "foster",
      "synergy",
      "holistic",
      "cutting-edge",
      "landscape",
      "empower",
      "not only that",
      "in conclusion",
    ],
  },

  flawlessYetEmpty: {
    minGenericOpeners: 2,
    genericOpeners: [
      "in a world where",
      "let's dive in",
      "lets dive in",
      "here's the thing",
      "heres the thing",
      "i'm excited to share",
      "im excited to share",
      "thrilled to announce",
      "i wanted to take a moment",
      "have you ever wondered",
      "picture this",
      "let that sink in",
      "food for thought",
      "the reality is",
      "here's a hard truth",
      "heres a hard truth",
      "stop scrolling",
      "hot take",
      "unpopular opinion",
      "let me be clear",
      "here's why",
      "heres why",
      "so what does this mean",
      "the future of",
    ],
  },
};
