var AIBlocker = AIBlocker || {};

AIBlocker.SETTINGS = {
  coverAllPosts: false,
  coverScoreThreshold: 25,
  coverMinParameters: 1,
  minTextLength: 80,
  scanDebounceMs: 300,
  debug: true,

  detectors: {
    buzzwordDensity: true,
    structuralTemplating: true,
    lackOfBurstiness: true,
    engagementBait: true,
    sycophanticTone: true,
    reportListicle: true,
  },

  buzzwordDensity: {
    fullPoints: 25,
    partialPoints: 10,
    fullMatchMin: 2,
    phrases: [
      "delve",
      "dive into",
      "leverage",
      "harness",
      "it's worth noting",
      "it is worth noting",
      "game-changer",
      "game changer",
      "unravel",
      "moreover",
      "furthermore",
      "in conclusion",
      "in today's fast-paced digital landscape",
      "in today's fast-paced",
      "in today's",
      "it's important to note",
      "it is important to note",
      "that being said",
      "needless to say",
      "it goes without saying",
      "when it comes to",
      "unlock the potential",
      "cutting-edge",
      "landscape",
      "major shift",
      "worth taking a look",
      "behind the scenes",
      "no meaningful",
      "the reality is",
      "at scale",
      "in a world",
    ],
  },

  structuralTemplating: {
    points: 25,
    minElements: 1,
    minEmojiBulletLines: 3,
    minFindingLines: 3,
    introLines: 3,
    bulletLines: 5,
    findingPrefixes: ["-->", "→", "—", "–"],
    hooks: [
      "here's what nobody tells you",
      "heres what nobody tells you",
      "nobody tells you",
      "stop scrolling",
      "hot take",
      "unpopular opinion",
      "here's why",
      "heres why",
      "here's the thing",
      "heres the thing",
      "let that sink in",
      "picture this",
      "have you ever wondered",
    ],
    hookPatterns: [
      /\bstop doing\b.{0,60}?\bstart doing\b/gi,
      /\bstop\b.{0,40}?\bstart\b/gi,
    ],
    emojiBullets: ["🚀", "🧠", "💡", "🔥", "✅"],
  },

  burstiness: {
    points: 25,
    minSentences: 3,
    minWords: 8,
    maxWords: 22,
    maxNarrowShare: 0.55,
  },

  engagementBait: {
    points: 15,
    phrases: [
      "agree?",
      "thoughts?",
      "what are your thoughts",
      "what do you think",
      "let me know in the comments",
      "let me know in the comments below",
      "drop a comment",
      "share your thoughts",
      "comment below",
      "your turn",
      "who else",
      "like if you",
      "am i the only one",
      "let me know",
      "curious to hear",
      "would love your",
      "hit follow",
    ],
  },

  sycophanticTone: {
    points: 10,
    minGenericOpeners: 1,
    minOptimisticPhrases: 1,
    genericOpeners: [
      "in a world where",
      "let's dive in",
      "lets dive in",
      "here's the thing",
      "heres the thing",
      "i'm excited to share",
      "im excited to share",
      "thrilled to announce",
      "i wanted to take a moment",
      "have you ever wondered",
      "picture this",
      "let that sink in",
      "food for thought",
      "the reality is",
      "here's a hard truth",
      "heres a hard truth",
      "the future of",
    ],
    optimisticPhrases: [
      "thrilled to",
      "incredibly",
      "truly honored",
      "grateful for the opportunity",
      "couldn't be more",
      "humbled to",
      "blessed to",
      "so excited",
      "deeply grateful",
      "it's an honor",
      "it is an honor",
      "beyond excited",
      "proud to share",
    ],
  },

  reportListicle: {
    points: 25,
    minElements: 1,
    minFindingLines: 3,
    closerPhrases: [
      "we're not yet sure",
      "we are not yet sure",
      "worth taking a look",
      "worth checking",
      "behind the scenes",
      "s/o to",
      "shout out to",
      "shout-out to",
      "on our team",
      "especially because",
      "identifying and investigating",
      "if you've been investing",
      "if youve been investing",
    ],
  },
};
